# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT28 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.8.1"

  depends_on "awscli"
  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.1/mortar_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "3c4061706dde593b539083360ece732a47b6d540ca7d39cfcf4528fd0146b671"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.1/mortar_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9a05a1bfc4732c2322e1a5a7ecb0cfdd6dae753dcff40d1e3535d74f5d5d9aea"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.1/mortar_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "4c706392f13894b30227efae20a0480ab3ca48b52ed616a085809219baad962a"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.1/mortar_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "7bb0e5db0e4d9a21a31955f5bf0091673f92e861ee7f034dfea1945eea410a0f"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
  end
end
