# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT23 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.3.4"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.3.4/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "fad0603291b889a2c4bbf4a4e2275d39e5a234a20b4357f52e13cd7b849f46d6"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.3.4/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "eb93692ff414b17bd9a493769f650ba74a71c856e6a6eeca6817191330babf56"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.3.4/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "764776e709db0242b6253c303a8e01f682dcb360875f3b4ef3e567e6898fed8d"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.3.4/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "547ae5678e6ced3edb545b2210a4db10ddf4279a0c5f5d4451a3cf3a5c54a4bb"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
  end

  test do
    system "mortar version"
  end
end
