# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mortar < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.7.3"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.3/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "5dd0738e3d1990f0b4b948859dd234b06a42bbc235b0838c9782f47e26d408e2"

      def install
        bin.install "mortar"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.3/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1462430a7027e039fa5b5bd9c0fd36ab05aaa7db8f62bb6a6b147cb86e4ee282"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.3/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "8108f16c28610ec5a39137bfcacf71a7d2cbcec3dff81657c0baa5bcc2192aa6"

        def install
          bin.install "mortar"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.3/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "a922b456f1b9206ac9d0308191fd9b8ef7da314a868358be880b49f09ee81199"

        def install
          bin.install "mortar"
        end
      end
    end
  end

  test do
    system "mortar version"
  end
end
