# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT2 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.8.0"

  depends_on "awscli"
  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.0/mortar_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "7ec3a8c01fe2e3e10a1a364414a9e9b0c37af2eb0667434945eb9acd51c916ea"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.0/mortar_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0e4bd6b17a2496a7a94b595c95a0e936d3da34ec36d77b9beeaa5a0b72b13c78"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.0/mortar_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "7593d7745b08f387b7ed815c5cc5c805393d53f8326a6ed8d7c8c52f2abde6f8"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.0/mortar_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "4028b31bdccda7c9e282c785670b765bd86afde4e32a7c3e40f55c611a878e9e"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
  end
end
