# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT15 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.5.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.5.4/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "beea0f9a2e895f9c3a904e16f4806d72928582162a91291512896caabe162483"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.5.4/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "872240a5819e9d99bde1489aa1c80198f84a8fc8086dcc4f4a61184d69eefe71"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.5.4/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f1e9043e9f0d35e89f8bc5ea6eaa78a67bcf07b09d7f9baa3e81ce22bfe5a9e3"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.5.4/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "855802c6bc6d0e3068464ffb8cf791c9a2299be4a7e78634808ad4057e982200"

      def install
        bin.install "mortar"
      end
    end
  end

  test do
    system "mortar version"
  end
end
