# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT1 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.7.8"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.8/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "41197ce4e676162ced9382806e13c80f9a987100024f9595c50d70dd0bdc6f70"

      def install
        bin.install "mortar"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.8/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2140be7c8704d31cfb8a4371ad037525fbce8d1a3655838b36c1f49a3a1357c2"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.8/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "a5247fa3ecb9b7d2ff50623a51a3b1d490b9043859ce737de1851eeb58028a6d"

        def install
          bin.install "mortar"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.8/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "4b5ff3e17e1a0f512eabb1a271293027e9c250396e4594888cba9c0503a941c3"

        def install
          bin.install "mortar"
        end
      end
    end
  end

  test do
    system "mortar version"
  end
end
