# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT17 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.7.7"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.7/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "059cfe8bf607b771d6ed9d700f3f8de4107548189fe6ae64b7f26334a1aa19e5"

      def install
        bin.install "mortar"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.7/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a1776b91b9a2422dd6b734738ba2fb3c617b05cec07cc782d6e5ab68c7b55b10"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.7/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "c332b528b3056b165896fdc471ae66df3d86e1c0b51be93ff573371c33c687da"

        def install
          bin.install "mortar"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.7/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "d570003eaddb49a4fa434e961c3cd860b62dfa1b4e7be20d3bcf3222a497f48c"

        def install
          bin.install "mortar"
        end
      end
    end
  end

  test do
    system "mortar version"
  end
end
