# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT16 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.6.0/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "83eb0042dd4fc0ca93132ca7a10b95a31b41f10781bd86167ac4320ab8188e1d"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.6.0/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e4e0798bd632f95d4977ee3863f208b05dd7630635dd3c20316a95ea103aa968"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.6.0/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b8aae75acbe68235d79e6c09d6e5ed79b58e8b1160729bbe61fdee4a9d3beaaf"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.6.0/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5ded21307b813ff4b5c545f3c96ec18e9f03ed22ffc1ed92cbae645857962ca7"

      def install
        bin.install "mortar"
      end
    end
  end

  test do
    system "mortar version"
  end
end
