# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Mortar < Formula
  desc "Mortar - build and use gRPC API easy"
  homepage "https://github.com/bucketplace/mortar-cli"
  version "1.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v1.3.2/mortar-cli_1.3.2_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f27cd886e95110633484b4edbaacf8987810dcb5552ef327af2b26d77a92c153"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v1.3.2/mortar-cli_1.3.2_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "86177b4c99b4f42d8cb0b46a090afacc2f8c7cf773011def7ed2548d4c331f50"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v1.3.2/mortar-cli_1.3.2_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0a729fb77e3404461845c52e9a7fc4edc2d7efe50018147966db351e672e1ab2"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v1.3.2/mortar-cli_1.3.2_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dc2e0aed72432a95f53530553f42462da54f8428ed3fcc28ba0b5d925e70ec7d"

      def install
        bin.install "mortar"
      end
    end
  end

  test do
    system "mortar version"
  end
end
