# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT22 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.2.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.2.9/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "bf718233c25fa2cc7e4cde8c7bd4ee7331c1de60815c9c30915c651ef4683fed"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.2.9/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c1e5de1eab6553c669c7a9b528b91eac6f406c0054b3032d0aacf9f1df16dc32"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.2.9/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0f2d009f18d7149759f79c21a7621d0292df41b7dba99d0c788da2d604656c3e"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.2.9/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6ffdfc72b2dc8b07c3607c3209107fba3b939088ffc412a2017c74df83e40321"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  test do
    system "mortar version"
  end
end
