# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT16 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.6.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.6.7/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ea69c2cb420085e72591de7cf6428ed7c93a704c714622c9320ec9b2827ef803"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.6.7/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "ee8affab967b8ab90d0e21cbc1c5138dc226c6b7148a4198baf44856ffadcf1a"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.6.7/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "199ae58886f4155c9600ca9f0ffb3b8e4d6b9d918cd1c6d31bce95e2427b55df"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.6.7/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6a071c02ac01dec994d8b95b3f22cdad036c2980f5cdd810289550d7fad0e07e"

      def install
        bin.install "mortar"
      end
    end
  end

  test do
    system "mortar version"
  end
end
