# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT22 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.2.3/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d2752a6e66b62272e566101831ebdbd3ea7b0dcccf65689f00ac9fb235c0109b"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.2.3/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5bf88427bbeaacbb88786832ec759b9536218cd9f14d07afe71e7debd4325a08"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.2.3/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8462033993bf15022def9a5784e3452f59de7a408caa8ab7a869cf8feea0c7ce"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.2.3/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "64a15f11c9d9e98d3fd003c375ed7e031fab3853e0d5d2f3c8f15e2dbf59d4f9"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  test do
    system "mortar version"
  end
end
