# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT17 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.7.6"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.6/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "29461b6c834a423ed12b1fe30ccbdc81107f8c9b97c9891a19cc014ed6fec57d"

      def install
        bin.install "mortar"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.6/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "34ed277f2fa8a29d4b0810b308bfa0eeae690226e133ff31090872d24b910856"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.6/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "546b2ca4c3c43bd185f1a24003acc45c7b5f1d1e848a3794ca134decabb0685f"

        def install
          bin.install "mortar"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.7.6/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "377e3fd168a867ecc48fe5b271d1f1d5dbe6fdd5a6a375cf7e42aa2b1f058c74"

        def install
          bin.install "mortar"
        end
      end
    end
  end

  test do
    system "mortar version"
  end
end
