# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mortar < Formula
  desc "Mortar - build and use gRPC API easy"
  homepage "https://github.com/bucketplace/mortar-cli"
  version "0.0.1-beta1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v0.0.1-beta1/mortar-cli_0.0.1-beta1_Darwin_x86_64.tar.gz"
      sha256 "c024ea86c4680c3ef5430bd3c0713e6fca1cc76da9e7e68f526b7d0dd0987523"
    end
    if Hardware::CPU.arm?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v0.0.1-beta1/mortar-cli_0.0.1-beta1_Darwin_arm64.tar.gz"
      sha256 "45dcc9c87899abdab128d37e8af0a9e534b38422e7d535670cd8b894a7f569fc"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v0.0.1-beta1/mortar-cli_0.0.1-beta1_Linux_x86_64.tar.gz"
      sha256 "518f801fa2d85a7d33f915344f30cba17d29d8bf80877e59361c9dc9b0faabf9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v0.0.1-beta1/mortar-cli_0.0.1-beta1_Linux_arm64.tar.gz"
      sha256 "eb8d71fd2982c03512789df95e705a2d93abe5d2f82fe31a443307eb1cc8d383"
    end
  end

  def install
    bin.install "mortar"
  end
end
