# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT14 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.4.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.14/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "cb20902869a0febaab0c9c6b0dbe61e8d39e20541384971b6b76e02eaa64960f"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.14/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "dac2042d1e37e88bf84aea0cabadff3ccc368e26825e307d2c137460147b6b7a"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.14/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0c805924738d7b019c746cba723fea7d933524ec466addb10a46b31f81d2b780"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.14/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "ea4e8ca7938f4bc331ba386f44a8eaebf74870f7b49d248de77ddd7957ee9e77"

      def install
        bin.install "mortar"
      end
    end
  end

  test do
    system "mortar version"
  end
end
