# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT21 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.1.3/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d5f25bf46d3641d9a2222ab817c9e0615a1ae3cb8652c7cc3d7d6fe5b66d2bc9"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.1.3/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "ec645f64a9b8d5b61e8fea33aeb3e12e02f001a298d658da1cff22e062d20df4"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.1.3/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "dda465e456e8615406d2220c01920940439308a3fdd8e6188ce5b72049279dad"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.1.3/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0161de522fe9e4ee498bc7ccdfbdaaf31fc62d8edc09abd337f36a35170834d7"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  test do
    system "mortar version"
  end
end
