# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT21 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.1.0/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "391a36d084424d9a9ce01cbe38549cf1b2c08d280e783dc6044e6f0cae33fc60"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.1.0/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1aca8621743b1a1fecc093ec92ec0ae498bffe66229f339b371de9e5758d2f7f"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.1.0/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a04b0b58643dc23fe672d51de2acc4b809b8ef98b1d61851fd2fc3a004a1fe70"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.1.0/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "204d287915246b0a187e5e03d75b7c5734089260b1fbb3056cbe091c3e61fd08"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  test do
    system "mortar version"
  end
end
