# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT25 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.5.22"

  depends_on "awscli"
  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.5.22/mortar_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "bccd141588254ac0dd8f4aa4fce08b179f52af400f6fb2584f6a263ddabe519f"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.5.22/mortar_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f1fb2e3b84bd469ae7d33f0b7664259521d09776ec43831cf31014b8ceef4198"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.5.22/mortar_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "885ad9fd2e578acc348e7b728d227b4fec6ae475d5b4c6b680a7de918f21a3d4"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.5.22/mortar_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "8860cbeb6981173c950cb5da2e6290e7ca1fe83506d9b293792b2888beae7fb5"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
  end
end
