# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT14 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.4.20"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.20/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "3b6df1cb2cadff0f8db0bb687d6cd182dcda5d2d771462186caf10bd58c1dab9"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.20/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2f7cf0f5273043173c167be68d1d6f97a5919cb5d2eaa052fd671923399fa1e7"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.20/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "440cd7474eb7d92a0f45aca174a976b24d7fb581f91ad08aa0d0e16ddba6f3b8"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.20/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "17f6d8c07dd653006f27495e1dd74a437370e528eea915e09f6509d34d08de6f"

      def install
        bin.install "mortar"
      end
    end
  end

  test do
    system "mortar version"
  end
end
