# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT25 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.5.2"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.5.2/mortar_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ea64beb2792fee252d032c699f82e845ca0abb8591f9fb0d18f8fc31bf4fe8b2"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.5.2/mortar_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "48a12445e53b619d905219ffbd4736b1daa41cd588aacf699834c62a1828a67d"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.5.2/mortar_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "921367fec19830b61776c888a74c58d87553e4cfbfb386d8329a485f8fa59981"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.5.2/mortar_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "7f5da2df143a595b1592220d171e0681c446aa2cac0d4599933e92d7cdcd2c04"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
  end

  def post_install
    system "mortar version"
  end

  test do
    system "mortar version"
  end
end
