# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Mortar < Formula
  desc "Mortar - build and use gRPC API easy"
  homepage "https://github.com/bucketplace/mortar-cli"
  version "1.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v1.3.6/mortar-cli_1.3.6_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c8148fec2d0307da4e20aa0c434baaab8ec83e7b1722dbc9b7afe7886d4f620c"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v1.3.6/mortar-cli_1.3.6_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6004f13ebfc011eaf4a817f951885fed465e02921152730f5b5e2da7164e4aaa"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v1.3.6/mortar-cli_1.3.6_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e360c1ba7d656672a4e4fcd7a114cf3a6e8cb2b2d5acecd28b58c01b213f7136"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bucketplace/mortar-cli/releases/download/v1.3.6/mortar-cli_1.3.6_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "674edf7b44aa1245ec9c6eaa0e8b205be77458361a2546d4fd11e9f99dc6d2f5"

      def install
        bin.install "mortar"
      end
    end
  end

  test do
    system "mortar version"
  end
end
