# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT14 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "1.4.22"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.22/mortar_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "5b5f3d0c4cbb93564f393785b5113f5f9229369edfb201188fa3669bf40ada71"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.22/mortar_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "56142e183efbc6ef2894a6812d32e9ccdb8f435d933a924381a408b4fcfac505"

      def install
        bin.install "mortar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.22/mortar_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e087baac33de34033bb5fa7d828f1fdff42b31111018dcf4e8679bd2c47e75c4"

      def install
        bin.install "mortar"
      end
    end
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/1.4.22/mortar_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "29f709e8d0b3bf969ac8ac3aaceaf89b8cc38768e6e726debfaf66cdac3a118e"

      def install
        bin.install "mortar"
      end
    end
  end

  test do
    system "mortar version"
  end
end
