# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MortarAT28 < Formula
  desc "Mortar - build and deploy your applications easy as eating a piece of cake"
  homepage "https://github.com/bucketplace/mortar"
  version "2.8.4"

  depends_on "awscli"
  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.4/mortar_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "9afe365cf3812a343245b2dd1acc2fa8a8e6742a203964f1360eaa4ef48e18ae"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
    on_arm do
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.4/mortar_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "940317af0f11aa0dbeef372326931eb7144212cb9cf1c3294774cd0984477c42"

      def install
        bin.install "mortar"
        prefix.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.4/mortar_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "22bffd04af00f3a1fdf25779da6ba10efe7ace90709ee5c9ac61fe0565147179"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/mortar/2.8.4/mortar_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "21d2ae9734fadc8b5bf4ac71f3817125c499d99f58943d4ac357824b2d37b886"

        def install
          bin.install "mortar"
          prefix.install "version"
        end
      end
    end
  end
end
