# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortalCli < Formula
  desc "Portal CLI - dev-portal command-line tool for humans and AI agents"
  homepage "https://github.com/bucketplace/dev-portal"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/portal-cli/0.1.0/portal-cli_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "7612f6861398d26deded1f0711bf733e8cee11b6375b7ec164945b8714cecaa6"

      define_method(:install) do
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/portal-cli/0.1.0/portal-cli_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2536d7ca68221eedc8cc648741ea34f53349f724501c5c6e7be21ee898088fa2"

      define_method(:install) do
        bin.install "portal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/portal-cli/0.1.0/portal-cli_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b93bb2a96b62f1bcf9f940e9dba88fb1e0d1fc828e0bdfa6746bb62859e08484"
      define_method(:install) do
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/portal-cli/0.1.0/portal-cli_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9a263cf1f3cfcdbc3f05fea947b10ca7e363803d3fc3007e16f37061abf72774"
      define_method(:install) do
        bin.install "portal"
      end
    end
  end
end
