# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortalCli < Formula
  desc "Portal CLI - dev-portal command-line tool for humans and AI agents"
  homepage "https://github.com/bucketplace/dev-portal"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/portal-cli/0.1.0/portal-cli_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "52324425255c244cde8cda3efe4e405917c7b0c63b940b6dd2cc3f5b95c8fb27"

      define_method(:install) do
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/portal-cli/0.1.0/portal-cli_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f9e8f0f7efffaa373d0f0c7e82ba7645424afc61efb5ea56251e3a8da20dc2d6"

      define_method(:install) do
        bin.install "portal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/portal-cli/0.1.0/portal-cli_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c5556900d6007857dd60357a5336e2d17d93300dd3bc15ac6fd1286d066f444d"
      define_method(:install) do
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://nexus.co-workerhou.se/repository/raw-tool-releases/homebrew/platform/portal-cli/0.1.0/portal-cli_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e03a7a82df1dd4277e351f4d23e9f6898e554a92e1d5cd33409e855bbf3c91d5"
      define_method(:install) do
        bin.install "portal"
      end
    end
  end
end
